# Generated by Django 5.2 on 2025-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepertech',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
