# Generated by Django 5.2 on 2025-05-05 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_keepertech_target_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeeperTech',
            new_name='Keeper',
        ),
        migrations.CreateModel(
            name='KeeperDailyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notification', models.TextField()),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeper.keeper')),
            ],
        ),
    ]
