# Generated by Django 5.2 on 2025-05-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_rename_keepertech_keeper_keeperdailynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeper',
            name='assignee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
