# Generated by Django 5.2 on 2025-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0006_alter_keeper_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeper',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
