# Generated by Django 5.2 on 2025-05-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0007_keeper_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeeperDailyNotification',
            new_name='KeeperDailyReminderAssistant',
        ),
    ]
