# Generated by Django 5.2 on 2025-05-18 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0008_rename_keeperdailynotification_keeperdailyreminderassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeperdailyreminderassistant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KeeperTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('delete', 'Delete'), ('update', 'Update')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeper.keeper')),
            ],
        ),
    ]
