# Generated by Django 5.2 on 2025-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0010_projectincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeper',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
